### ISSUE TITLE
Research about API security(DDOS etc) and come up with recommendations

### ISSUE THREAD

**Issue by prasadpilla** [solocoinapp/solocoin-backend#49]
Notes from JB,

saw this and not sure how much you've looked into but I'll share a few thoughts.

Research about API security(DDOS etc) and come up with recommendations

https://www.cloudflare.com/ is a free solution that protects against ddos at the dns level. 

and https://github.com/kickstarter/rack-attack is a nice middleware to help as well if for some reason cloudflare isn't an option

**Comment by nronas** [comment]
Will have a look on this

**Comment by prasadpilla** [comment]
@nronas Thanks for looking into this, would be great to have this in place before the public launch i.e 2 days from now. Counting the times Google folks take ti review the app.
