### ISSUE TITLE
Throttle all paths, not just auth endpoints

### ISSUE THREAD

**Issue by prasadpilla** [solocoinapp/solocoin-backend#59]
Anyone can use any path to DDOS for example /foo (even though it returns 404, it can still be used to DDOS).

So let's throttle all the paths.

**Comment by nronas** [comment]
As mentioned in the chat, we are throttling all endpoints with 40rpm https://github.com/solocoinapp/solocoin-backend/blob/master/config/initializers/rack_attack.rb#L17
