### ISSUE TITLE
Implement Daily Quiz API

### ISSUE THREAD

**Issue by nronas** [solocoinapp/solocoin-backend#60]
From docs: https://www.guilded.gg/SoloCoin/groups/6DMGMP1z/channels/5a639ffb-a9aa-4180-a9e8-9e343c245d47/docs/897845493

```
Daily Quiz - Once a user answers a question. They'll get set amount of rewards, say 50coins. There will be 2hr time limit before they can asnwer another question. (Meaning after they answer a question, they can't answer another question. there'll be a screen instead of quiz, that'll show come back after 2 hrs. (add timer of 02:00 for better engagement) @Android Dev
```

Implement an API that will support question management operations(fetching question + answer, submit answer + rewards)

**NOTE** : Questions and Answers will be managed by our CMS that will live in admin.

**Comment by MohdAnas** [comment]
Done.
