### ISSUE TITLE
Implement Admin with CMS

### ISSUE THREAD

**Issue by nronas** [solocoinapp/solocoin-backend#63]
from docs: https://docs.google.com/document/d/191QtN4He4Z3i6apTddNpHBBGOE3qBwKKU-W7ESBdeZs/edit

`
Web Dashboard CMS
Now we also need a web based dashboard connected to backend and frontend where any team member can add or remove rewards, challenges for more user friendly backend experience. Design team needs to develop a prototype for this
`

**Comment by MohdAnas** [comment]
Arbob has already shared a screenshot in the group. Please check and confirm so that I can go ahead with the design.
![Screenshot from 2020-05-10 16-51-30](https://user-images.githubusercontent.com/2948930/81499024-0d360980-92e6-11ea-81e9-d37f3e4d8fc1.png)

**Comment by MohdAnas** [comment]
I am done with it and deployed it to heroku.
